#ifndef GAME_GLOBAL
#define GAME_GLOBAL

#define MAX_VOLUME_LEVEL 20
#define MIN_VOLUME_LEVEL 0

#define MAX_SENSITIVITY_LEVEL 20
#define MIN_SENSITIVITY_LEVEL 0


extern int SETTINGS_VOLUME_LEVEL;
extern int SETTINGS_SENSITIVITY_LEVEL;

#endif